name: Deploy Secrets

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use the appropriate Node.js version for your project

      - name: Inject environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "VITE_SUPABASE_URL=${SUPABASE_URL}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" >> .env


      - name: Deploy Secrets
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Replace './dist' with your build output directory
